version: '3.3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  mongo-provisioning:
    build: ./db
    links:
      - mongodb
  api:
    build:
      context: ./api
    ports:
      - "3030:3030"
    links:
      - mongodb
  interface:
    build:
      context: ./interface
    ports:
      - "8080:80"
    links:
      - api

